# move_base_params.yaml

# Global costmap parameters
global_costmap:
  global_frame: "map"
  robot_base_frame: "bot6/base_footprint"
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  static_map: true
  rolling_window: false
  width: 10.0
  height: 10.0
  resolution: 0.05

  obstacle_range: 2.5
  raytrace_range: 3.0

  inflation_layer:
    inflation_radius: 0.5

  observation_sources: laser_scan

  laser_scan:
    data_type: "LaserScan"
    topic: "/bot6/scan" 
    marking: true
    clearing: true

# Local costmap parameters
local_costmap:
  global_frame: "bot6/odom"  
  robot_base_frame: "bot6/base_footprint"
  update_frequency: 30.0
  publish_frequency: 30.0
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

  obstacle_range: 2.5
  raytrace_range: 3.0

  inflation_layer:
    inflation_radius: 0.5

  observation_sources: laser_scan

  laser_scan:
    data_type: "LaserScan"
    topic: "/bot6/laser_scan" 
    marking: true
    clearing: true

# Planner parameters
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.3
  acc_lim_x: 0.5
  acc_lim_theta: 1.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
